### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by val-windfalldata** [gocardless/pgreplay-go#11]
Where is the observability Grafana dashboard ? I don't see it included in the repo, and I also don't see it anywhere when I search google

**Comment by val-windfalldata** [comment]
@lawrencejones where can I find the observability Grafana dashboard that you talk about in the README ?

**Comment by lawrencejones** [comment]
Ah sorry I missed this, must've dropped out of my emails!

I'm no longer at GoCardless, so I can't access their grafana instance.

If you ask @benwh he may be able to provide you a copy of the dashboard JSON, if the dashboard is still around!

**Comment by val-windfalldata** [comment]
thank you @lawrencejones ! @benwh can you please point me to where I can get the observability dashboard that this project's README talks about? I can't find it anywhere

**Comment by benwh** [comment]
Hey @val-windfalldata

Please check out the updated README, I've added a bit of information there as well as linked to the Grafana dashboard.
